[mypy]
python_version = 3.11
strict = false
warn_return_any = false
explicit_package_bases = true
ignore_missing_imports = true
exclude = apps/agents
disable_error_code = 
    arg-type,
    call-overload,
    no-untyped-def,
    no-any-return,
    type-arg,
    valid-type,
    union-attr,
    operator,
    index,
    return-value,
    misc,
    attr-defined,
    assignment,
    unused-ignore,
    str-unpack,
    syntax