-- Schema alignment from the 2026-08-18 remediation audit.
--
-- Brings an existing database in line with the canonical 01-schema.sql:
--  1) anomalies.deviation_score / tolerance_threshold widened NUMERIC(5,4) ->
--     NUMERIC(8,4): deviation ratios (count/max activations, days off schedule)
--     can exceed 9.9999 and would otherwise raise a numeric overflow at INSERT.
--  2) NOT NULL on columns the Pydantic models already require (anomalies.pattern_id,
--     recommendations.hypothesis_id, contexts.coherence_score,
--     patterns.strength_measure, hypotheses.coherence_score,
--     confidence_scores.calibration_justification, confidence_scores.calibration_error_estimate,
--     reports.content, observations.unit). All code paths always provide these
--     values; the constraints make the model contract explicit at the data layer.
--  3) reports.ai_generated DEFAULT FALSE: the Report Generator is an external
--     non-canonical capability (ADR-0002) that never produces AI-generated
--     output; the previous TRUE default could silently mark a report as
--     AI-generated when the column was omitted.
--
-- Notes:
--  * The FK actions (ON DELETE SET NULL on pattern_id/hypothesis_id) are NOT
--    changed here: they can never fire because the referenced rows are
--    immutable (DELETE blocked by their content triggers). With NOT NULL, any
--    hypothetical delete would also fail the NOT NULL constraint.
--  * Each statement is idempotent. ALTER ... SET NOT NULL fails only if
--    existing rows contain NULL in the column; none do (all inserts always
--    provide these values).

-- 1) Widen anomaly deviation columns (overflow risk).
ALTER TABLE anomalies ALTER COLUMN deviation_score TYPE NUMERIC(8,4);
ALTER TABLE anomalies ALTER COLUMN tolerance_threshold TYPE NUMERIC(8,4);

-- 2) Model-required columns -> NOT NULL.
ALTER TABLE anomalies ALTER COLUMN pattern_id SET NOT NULL;
ALTER TABLE recommendations ALTER COLUMN hypothesis_id SET NOT NULL;
ALTER TABLE contexts ALTER COLUMN coherence_score SET NOT NULL;
ALTER TABLE patterns ALTER COLUMN strength_measure SET NOT NULL;
ALTER TABLE hypotheses ALTER COLUMN coherence_score SET NOT NULL;
ALTER TABLE confidence_scores ALTER COLUMN calibration_justification SET NOT NULL;
ALTER TABLE confidence_scores ALTER COLUMN calibration_error_estimate SET NOT NULL;
ALTER TABLE reports ALTER COLUMN content SET NOT NULL;
ALTER TABLE observations ALTER COLUMN unit SET NOT NULL;

-- 3) reports are never AI-generated by default.
ALTER TABLE reports ALTER COLUMN ai_generated SET DEFAULT FALSE;